# Generated by Django 2.2.3 on 2019-08-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190829_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='riddle',
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил оценку'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
